Repository intersective/app, pull requests merged in 2019-01, with the labels that each got.

#62 [AV2-59] Review Rating UI and Service
  src/app/app.module.ts
  src/app/assessment/assessment.component.ts
  src/app/review-rating/review-rating.component.html
  src/app/review-rating/review-rating.component.scss
  src/app/review-rating/review-rating.component.spec.ts
  src/app/review-rating/review-rating.component.ts
  src/app/review-rating/review-rating.service.ts
  src/app/services/storage.service.ts
  src/app/shared/notification/notification.module.ts
  src/app/shared/notification/notification.service.ts
  src/app/switcher/switcher.service.ts
Labels: ready for code review

#64 [AV2-120]login fail redirect to program selection
  package-lock.json
  package.json
  src/app/auth/auth-login/auth-login.component.html
  src/app/auth/auth-login/auth-login.component.ts
  src/app/auth/auth.service.ts
Labels: ready for code review

#86 circular dependent fix
  .gitignore
  ionic.config.json
  src/app/activity/activity.component.ts
  src/app/assessment/assessment.component.ts
  src/app/assessment/assessment.module.ts
  src/app/assessment/assessment.service.ts
  src/app/review-rating/review-rating.component.ts
  src/app/review-rating/review-rating.service.ts
  src/app/settings/settings.component.ts
  src/app/shared/notification/notification.module.ts
  src/app/shared/notification/notification.service.ts
Labels: changes required

#72 [AV2-135] Setting Page issues
  src/app/settings/settings.component.html
  src/app/settings/settings.component.ts
Labels: WIP

#80 [AV2-131]direct link login
  src/app/app.component.ts
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
  src/app/auth/auth-registration/auth-registration.component.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/auth.service.spec.ts
  src/app/auth/auth.service.ts
  src/app/services/storage.service.ts
  src/app/switcher/switcher.service.ts
Labels: ready for code review

#89 [AV2-130]implement file preview functionality of filestack
  README.md
  src/app/shared/filestack/filestack.module.ts
  src/app/shared/filestack/filestack.service.ts
  src/app/shared/filestack/preview/preview.component.css
  src/app/shared/filestack/preview/preview.component.html
  src/app/shared/filestack/preview/preview.component.ts
  src/app/topic/topic.component.ts
  src/app/topic/topic.module.ts
Labels: ready for code review

#104 [AV2-139]registration link format
  src/app/app.component.ts
  src/app/auth/auth-registration/auth-registration.component.ts
  src/app/auth/auth-routing.module.ts
Labels: ready for code review

#119 [AV2-150]email with "+" can't login
  src/app/auth/auth.service.ts
  src/app/home/home.component.ts
  src/app/shared/request/request.service.ts
  src/app/tabs/tabs.component.ts
Labels: ready for code review

#98 [AV2-136]display correct answers after submitting quiz
  src/app/assessment/assessment.service.ts
  src/app/questions/file/file.component.html
  src/app/questions/multiple/multiple.component.html
  src/app/questions/oneof/oneof.component.html
  src/app/questions/text/text.component.html
  src/styles.scss
Labels: ready for code review

#97 Feature/0.1/av2 84/project service
  package-lock.json
  src/app/activity/activity.component.html
  src/app/home/home.component.ts
  src/app/home/home.service.ts
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/project/project.component.ts
  src/app/project/project.module.ts
  src/app/project/project.service.ts
  src/app/tabs/tabs-routing.module.ts
  src/theme/variables.scss
Labels: changes required

#40 [AV2-58] Feature/0.1/av2 58/fast feedback
  .editorconfig
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/fast-feedback/fast-feedback.component.html
  src/app/fast-feedback/fast-feedback.component.scss
  src/app/fast-feedback/fast-feedback.component.spec.ts
  src/app/fast-feedback/fast-feedback.component.ts
  src/app/fast-feedback/fast-feedback.module.ts
  src/app/fast-feedback/fast-feedback.service.ts
  src/app/fast-feedback/question/question.component.html
  src/app/fast-feedback/question/question.component.ts
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/shared/notification/notification.service.ts
  src/app/tabs/tabs.component.ts
Labels: ready for code review

#122 [AV2-152]submission answer format issue
  src/app/assessment/assessment.service.ts
Labels: ready for code review

#131 vulnerable-dependencies fix
  package-lock.json
  package.json
Labels: ready for code review

#65 [AV2-114] Reset Password/Forgot password UI and serivce
  src/app/app.component.ts
  src/app/auth/auth-forgot-password/auth-forgot-password.component.html
  src/app/auth/auth-forgot-password/auth-forgot-password.component.ts
  src/app/auth/auth-reset-password/auth-reset-password.component.html
  src/app/auth/auth-reset-password/auth-reset-password.component.scss
  src/app/auth/auth-reset-password/auth-reset-password.component.spec.ts
  src/app/auth/auth-reset-password/auth-reset-password.component.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/auth.service.ts
Labels: ready for code review

#132 [AV2-161]Navigation issue
  src/app/activity/activity.component.ts
  src/app/assessment/assessment.component.html
  src/app/assessment/assessment.component.ts
  src/app/home/home.component.ts
  src/app/project/project.component.ts
  src/app/questions/file/file.component.html
  src/app/questions/multiple/multiple.component.html
  src/app/questions/oneof/oneof.component.html
  src/app/questions/text/text.component.html
  src/app/services/router-enter.service.ts
  src/app/settings/setting.service.ts
  src/app/settings/settings.component.ts
  src/app/switcher/switcher-program/switcher-program.component.ts
  src/app/tabs/tabs.component.ts
  src/app/topic/topic.component.html
  src/app/topic/topic.component.ts
Labels: ready for code review

#135 [AV2-160]Need to be able to display "team member selector" type of question
  src/app/assessment/assessment.component.html
  src/app/assessment/assessment.service.ts
  src/app/questions/questions.module.ts
  src/app/questions/team-member-selector/team-member-selector.component.html
  src/app/questions/team-member-selector/team-member-selector.component.scss
  src/app/questions/team-member-selector/team-member-selector.component.ts
  src/app/topic/topic.module.ts
Labels: ready for code review

#144 [AV2-156]Add information button to display choice description for multiple & checkbox question
  src/app/assessment/assessment.component.html
  src/app/assessment/assessment.component.scss
  src/app/assessment/assessment.component.ts
  src/app/assessment/assessment.service.ts
  src/app/shared/notification/pop-up/pop-up.component.html
Labels: ready for code review

#145 [AV2-155]screen freezes after marking feedback as read and review rating is not shown
  src/app/app.module.ts
  src/app/assessment/assessment.module.ts
  src/app/assessment/assessment.service.ts
  src/app/review-rating/review-rating.component.html
  src/app/review-rating/review-rating.module.ts
Labels: ready for code review

#115 [AV2-75] Multiple lines on chat
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/chat/chat-list/chat-list.component.html
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.scss
  src/app/chat/chat-room/chat-room.component.spec.ts
  src/app/chat/chat-room/chat-room.component.ts
  src/app/chat/chat.module.ts
  src/app/home/todo-card/todo-card.component.scss
  src/app/shared/pipes/linkify/linkify.pipe.spec.ts
  src/app/shared/pipes/linkify/linkify.pipe.ts
  src/app/shared/shared.module.ts
  src/theme/variables.scss
Labels: ready for code review

#155 [AV2-165] fastfeedback refactored
  src/app/assessment/assessment.component.ts
  src/app/assessment/assessment.service.ts
  src/app/fast-feedback/fast-feedback.component.ts
  src/app/fast-feedback/fast-feedback.service.ts
  src/app/home/home.component.ts
Labels: ready for code review

#152 [AV2-167]Issues when switching the program and custom branding
  src/app/activity/activity.component.ts
  src/app/app.component.ts
  src/app/assessment/assessment.component.ts
  src/app/home/home.component.ts
  src/app/home/home.service.ts
  src/app/page-not-found/page-not-found.component.html
  src/app/project/project.component.ts
  src/app/services/router-enter.service.ts
  src/app/settings/settings.component.ts
  src/app/switcher/switcher-program/switcher-program.component.ts
  src/app/tabs/tabs.component.ts
  src/app/topic/topic.component.ts
Labels: ready for code review

#161 [AV2-165] fixed null param
  src/app/fast-feedback/fast-feedback.component.ts
Labels: bug

#156 [AV2-92] feature/pusher module
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/auth.service.ts
  src/app/fast-feedback/fast-feedback.service.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/home/home.service.ts
  src/app/project/project.component.ts
  src/app/services/utils.service.ts
  src/app/settings/settings.component.ts
  src/app/shared/pusher/pusher.module.ts
  src/app/shared/pusher/pusher.service.ts
  src/app/switcher/switcher-program/switcher-program.component.ts
  src/app/tabs/tabs.component.html
  src/app/tabs/tabs.component.ts
  src/app/tabs/tabs.module.ts
  src/app/topic/topic.service.ts
  src/environments/environment.local.ts
  src/environments/environment.prod.ts
  src/environments/environment.stage.ts
  src/environments/environment.ts
Labels: WIP

#183 [AV2-187]/add timeformater to the review timestamp
  package-lock.json
  src/app/home/home.service.ts
  src/app/reviews/reviews.component.html
  src/app/reviews/reviews.service.ts
  src/app/services/utils.service.ts
Labels: changes required

#59 Feature/0.1/av2 83/chat services
  package-lock.json
  src/app/chat/chat-list/chat-list.component.html
  src/app/chat/chat-list/chat-list.component.scss
  src/app/chat/chat-list/chat-list.component.ts
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.scss
  src/app/chat/chat-room/chat-room.component.ts
  src/app/chat/chat-routing.module.ts
  src/app/chat/chat.service.ts
  src/app/shared/request/request.interceptor.ts
Labels: ready for code review
