Repository intersective/app, pull requests merged in 2019-09, with the labels that each got.

#524 [AV2-426] Alignment issues in milestone page when platform changed.
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/shared/components/activity-card/activity-card.component.scss
Labels: ready for code review

#533 [AV2-432] Alignment issue on the home page
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/shared/components/activity-card/activity-card.component.scss
  src/app/shared/components/description/description.component.scss
Labels: ready for code review

#559 [AV2-381] Feature/enhanced continue dev
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/assessment/assessment.component.html
  src/app/assessment/assessment.component.ts
  src/app/assessment/assessment.service.ts
  src/app/fast-feedback/fast-feedback.component.html
  src/app/fast-feedback/fast-feedback.component.ts
  src/app/fast-feedback/fast-feedback.service.ts
  src/app/shared/components/icon/icon.component.html
  src/app/shared/components/icon/icon.component.ts
  src/app/shared/notification/custom-toast/custom-toast.component.html
  src/app/shared/notification/custom-toast/custom-toast.component.scss
  src/app/shared/notification/custom-toast/custom-toast.component.spec.ts
  src/app/shared/notification/custom-toast/custom-toast.component.ts
  src/app/shared/notification/notification.module.ts
  src/app/shared/notification/notification.service.ts
  src/app/topic/topic.component.html
  src/app/topic/topic.component.ts
  src/app/topic/topic.module.ts
  src/assets/checkmark.svg
  src/styles.scss
Labels: WIP

#556 New Relic integration
  .gitignore
  README.md
  angular.json
  src/assets/newrelic.js
  src/index.html
  src/index.prod.html
  src/scripts/newrelic.js.dev
  src/scripts/newrelic.js.prod
Labels: ready for testing

#564 Feature/full integration new relic experiment
  angular.json
  package-lock.json
  package.json
  src/app/activity/activity.component.ts
  src/app/app.module.ts
  src/app/assessment/assessment.component.ts
  src/app/auth/auth-login/auth-login.component.ts
  src/app/auth/auth-logout/auth-logout.component.ts
  src/app/home/home.component.ts
  src/app/project/project.component.ts
  src/app/shared/new-relic/new-relic.module.ts
  src/app/shared/new-relic/new-relic.service.ts
  src/app/switcher/switcher-program/switcher-program.component.ts
  src/app/tabs/tabs.component.ts
  src/index.html
  src/index.prod.html
Labels: WIP

#567 [AV2-447] Activity List / Detail Accessibility Fix
  src/app/activity/activity.component.html
  src/app/activity/activity.component.scss
  src/app/project/project.component.html
  src/app/shared/components/activity-card/activity-card.component.html
  src/app/shared/components/activity-card/activity-card.component.scss
  src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.html
Labels: ready for code review

#568 [AV2-449] Chat List / Messages Accessibility fix
  src/app/chat/chat-list/chat-list.component.html
  src/app/chat/chat-preview/chat-preview.component.html
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.ts
Labels: ready for code review
