Repository intersective/app, pull requests merged in 2019-10, with the labels that each got.

#560 [AV2-463] Feature/fuller newrelic integration
  package-lock.json
  package.json
  src/app/achievements/achievements.component.spec.ts
  src/app/achievements/achievements.component.ts
  src/app/activity/activity.component.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/assessment/assessment.component.spec.ts
  src/app/assessment/assessment.component.ts
  src/app/auth/auth-forgot-password/auth-forgot-password.component.spec.ts
  src/app/auth/auth-forgot-password/auth-forgot-password.component.ts
  src/app/auth/auth-login/auth-login.component.spec.ts
  src/app/auth/auth-login/auth-login.component.ts
  src/app/auth/auth-logout/auth-logout.component.ts
  src/app/auth/auth-registration/auth-registration.component.ts
  src/app/chat/chat-list/chat-list.component.ts
  src/app/chat/chat-room/chat-room.component.ts
  src/app/events/events.component.spec.ts
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/project/project.component.spec.ts
  src/app/project/project.component.ts
  src/app/project/project.service.spec.ts
  src/app/services/storage.service.ts
  src/app/settings/settings.component.ts
  src/app/shared/new-relic/new-relic.module.ts
  src/app/shared/new-relic/new-relic.service.spec.ts
  src/app/shared/new-relic/new-relic.service.ts
  src/app/switcher/switcher-program/switcher-program.component.ts
  src/app/switcher/switcher.service.ts
  src/app/tabs/tabs.component.ts
  src/app/topic/topic.component.ts
  src/assets/newrelic.js
  src/index.html
  src/index.prod.html
  src/karma.conf.aws.js
  src/karma.conf.js
  src/testing/mocked.service.ts
  src/typings.d.ts
Labels: WIP

#528 [AV2-390] Customise the toast message
  src/app/assessment/assessment.component.ts
  src/app/assessment/assessment.service.spec.ts
  src/app/assessment/assessment.service.ts
  src/app/shared/notification/notification.service.ts
Labels: ready for code review

#566 [AV2-443] Autosave not available
  src/app/assessment/assessment.component.html
  src/app/assessment/assessment.component.spec.ts
  src/app/assessment/assessment.component.ts
Labels: changes required

#594 [AV2-468] re-add for missed button
  src/app/assessment/assessment.component.html
Labels: ready for code review, ready for testing

#593 [AV2-458] Experience Switcher Enhancement
  src/app/shared/components/clickable-item/clickable-item.component.html
  src/app/shared/components/clickable-item/clickable-item.component.scss
  src/app/shared/components/clickable-item/clickable-item.component.ts
  src/app/switcher/switcher-program/switcher-program.component.html
  src/app/switcher/switcher-program/switcher-program.component.scss
Labels: ready for code review

#574 [AV2-448] Assessments and Reviews, Pulse Checks and Review Ratings and Topics
  src/app/assessment/assessment.component.html
  src/app/questions/oneof/oneof.component.html
  src/app/questions/team-member-selector/team-member-selector.component.html
  src/app/questions/text/text.component.html
  src/app/review-rating/review-rating.component.html
  src/app/reviews/reviews.component.html
Labels: ready for code review

#595 [AV2-486] check action and review.status
  package-lock.json
  src/app/assessment/assessment.component.spec.ts
  src/app/assessment/assessment.component.ts
  src/app/services/router-enter.service.ts
  src/testing/mocked.service.ts
Labels: WIP

#604 [AV2-489] Hotfix/event checking
  src/app/assessment/assessment.component.ts
  src/app/events/events.component.html
  src/app/events/events.component.ts
Labels: ready for code review, ready for testing
