Repository intersective/app, pull requests merged in 2019-08, with the labels that each got.

#480 [AV2-336]reset password check [To Master]
  src/app/auth/auth-forgot-password/auth-forgot-password.component.ts
Labels: ready for testing on Develop

#486 [AV2-367]Same achievement pops up twice [To Master]
  src/app/app.component.ts
Labels: ready for testing on Develop

#489 [AV2-367]Same achievement pops up twice [To Master]
  src/app/app.component.ts
  src/app/services/shared.service.ts
  src/app/services/storage.service.ts
Labels: ready for testing on Develop

#491 Bug/av2 374/update description related to program config
  src/app/services/storage.service.ts
  src/app/shared/components/description/description.component.html
  src/app/shared/components/description/description.component.ts
  src/app/switcher/switcher.service.ts
Labels: ready for code review

#483 [AV2-311] 'Submitted by' displayed before submission
  src/app/assessment/assessment.component.html
  src/app/services/utils.service.ts
  src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.scss
  src/styles.scss
Labels: ready for code review

#498 [AV2-379]reviews for mentor not loaded
  src/app/activity/activity.service.ts
  src/app/assessment/assessment.service.ts
Labels: ready for testing

#506 Bug/av2 348/video continues to play after exiting the topic
  src/app/assessment/assessment.component.ts
  src/app/services/shared.service.ts
  src/app/tabs/tabs.component.ts
  src/app/topic/topic.component.ts
Labels: ready for code review

#503 Feature/av2 199/extend chat message window
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.scss
  src/app/chat/chat.module.ts
  src/app/shared/directives/autoresize/autoresize.directive.spec.ts
  src/app/shared/directives/autoresize/autoresize.directive.ts
  src/app/shared/shared.module.ts
Labels: ready for code review

#518 [AV2-199] Chat enhancement -extend chat message window
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.scss
  src/app/chat/chat-room/chat-room.component.ts
  src/app/chat/chat.module.ts
  src/app/shared/directives/autoresize/autoresize.directive.ts
  src/app/shared/shared.module.ts
Labels: ready for testing

#519 [AV2-424] Hotfix/directlink-autologin
  src/app/app.component.ts
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.service.ts
Labels: ready for code review

#522 [AV2-382] Padding fix on milestone page
  src/app/project/project.component.html
  src/app/project/project.component.scss
Labels: ready for code review
