Repository intersective/app, pull requests merged in 2020-01, with the labels that each got.

#667 [AV2-535] Bugfix/submiter-reviewer-compulsory-question
  src/app/assessment/assessment.component.spec.ts
  src/app/assessment/assessment.component.ts
  src/app/services/utils.service.ts
Labels: ready for code review, ready for testing

#672 [AV2-528] Bugfix/clickable-slides
  src/app/overview/home/home.component.html
  src/app/overview/home/home.component.scss
  src/app/overview/home/home.component.ts
  src/app/overview/home/slidable/slidable.component.html
  src/app/overview/home/slidable/slidable.component.scss
  src/app/overview/home/slidable/slidable.component.ts
  src/app/overview/home/todo-card/todo-card.component.html
  src/app/overview/home/todo-card/todo-card.component.scss
Labels: ready for code review, ready for testing

#674 [AV2-556] topic video start playing after navigate to dashboard
  src/app/services/shared.service.ts
Labels: ready for code review

#681 [AV2-562] Bugfix/notification-cards-gap
  src/app/overview/home/home.component.html
  src/app/overview/home/home.component.scss
  src/app/overview/home/home.component.spec.ts
  src/app/overview/home/home.component.ts
  src/app/overview/home/home.service.spec.ts
  src/app/overview/overview-routing.module.ts
  src/app/overview/overview.component.html
  src/app/overview/overview.component.scss
  src/app/overview/overview.component.spec.ts
  src/app/overview/overview.component.ts
  src/app/overview/overview.module.ts
  src/app/overview/project/project.component.spec.ts
  src/testing/activated-route-stub.ts
Labels: WIP

#683 [AV2-369] ui & text changes
  src/app/questions/file/file-display/file-display.component.html
  src/app/questions/file/file-display/file-display.component.scss
Labels: ready for testing

#684 [AV2-536] a participant is able to progress to a team assessment if not in a team
  src/app/activity/activity.service.ts
Labels: ready for code review

#686 added one more step to check roles
  package-lock.json
  src/app/assessment/assessment.component.spec.ts
  src/app/assessment/assessment.component.ts
Labels: ready for code review, ready for testing

#690 [AV2-558]Desktop View - Login
  src/app/auth/auth-login/auth-login.component.html
  src/app/auth/auth-login/auth-login.component.ts
  src/app/shared/components/branding-logo/branding-logo.component.html
  src/styles.scss
Labels: ready for code review

#695 [AV2-559]Desktop View - Registration
  src/app/auth/auth-registration/auth-registration.component.html
  src/app/auth/auth-registration/auth-registration.component.scss
  src/app/auth/auth-registration/auth-registration.component.ts
  src/styles.scss
Labels: ready for code review

#694 [AV2-557] show more/less does not look to be clickable
  src/app/shared/components/description/description.component.html
  src/app/shared/components/description/description.component.scss
Labels: ready for code review

#698 [AV2-565]Desktop View - Event navigation from activity
  src/app/event-detail/event-detail.component.html
  src/app/event-list/event-list.component.html
  src/app/event-list/event-list.component.ts
  src/app/events/events.component.html
Labels: ready for code review

#700 [AV2-560]Desktop View - Forget password and password reset
  src/app/auth/auth-forgot-password/auth-forgot-password.component.html
  src/app/auth/auth-login/auth-login.component.html
  src/app/auth/auth-reset-password/auth-reset-password.component.html
  src/app/auth/auth-reset-password/auth-reset-password.component.scss
  src/app/auth/auth-reset-password/auth-reset-password.component.ts
  src/styles.scss
Labels: ready for code review

#701 [AV2-505] redirect user to registration page from direct link
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
Labels: WIP

#702 [AV2-550]looking for a way to resolve displaying large number of events in the app
  src/app/event-list/event-list.component.html
  src/app/event-list/event-list.component.ts
Labels: ready for code review

#706 [AV2-505] redirect user to registration page from direct link
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
  src/app/switcher/switcher.service.ts
Labels: ready for code review

#711 [AV2-571] Desktop View - topic videos
  src/app/topic/topic.component.html
  src/app/topic/topic.component.scss
  src/app/topic/topic.component.ts
  src/styles.scss
Labels: ready for code review

#707 [AV2-567]Create skeleton screens - activities list
  src/app/overview/project/project.component.html
  src/app/overview/project/project.component.scss
  src/app/overview/project/project.component.ts
  src/app/overview/project/project.service.ts
  src/app/shared/components/activity-card/activity-card.component.html
  src/app/shared/components/activity-card/activity-card.component.scss
  src/styles.scss
Labels: ready for code review

#716 [AV2-580] Desktop View and mobile - Dashboard UI Issues
  src/app/overview/home/home.component.html
  src/app/overview/home/home.component.scss
  src/app/overview/project/project.component.html
Labels: ready for code review

#718 [AV2-584] Desktop -topics with no text content still have blank white box
  src/app/topic/topic.service.ts
Labels: ready for code review
