Repository intersective/app, pull requests merged in 2020-03, with the labels that each got.

#765 [AV2-603] topic back button confirmation button display red messages
  src/app/topic/topic.component.ts
Labels: ready for code review

#762 [AV2-601] WCAG color requirements
  src/app/event-list/event-list.component.html
  src/app/questions/file/file.component.html
  src/app/questions/multiple/multiple.component.html
  src/app/questions/multiple/multiple.component.scss
  src/app/questions/oneof/oneof.component.html
  src/app/questions/oneof/oneof.component.scss
  src/app/questions/team-member-selector/team-member-selector.component.html
  src/app/questions/team-member-selector/team-member-selector.component.scss
  src/app/questions/text/text.component.html
  src/app/shared/components/list-item/list-item.component.scss
  src/app/tabs/tabs.component.html
  src/app/tabs/tabs.component.scss
  src/theme/pfas/_colors.scss
  src/theme/pfas/_ionic-components.scss
  src/theme/variables.scss
Labels: changes required

#770 [AV2-601] WCAG color requirements
  src/theme/pfas/_ionic-components.scss
Labels: ready for code review

#773 [AV2-602] show more/less does not act with the configuration
  src/app/shared/components/description/description.component.ts
Labels: ready for code review

#781 [AV2-604]investigate the upgrade from ionic 4 to ionic 5
  package-lock.json
  package.json
  src/app/activity/activity.component.html
  src/app/activity/activity.component.ts
  src/app/chat/chat-list/chat-list.component.html
  src/app/chat/chat-list/chat-list.component.scss
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.ts
  src/app/event-detail/event-detail.component.html
  src/app/event-list/event-list.component.html
  src/app/events/events.component.html
  src/app/overview/home/todo-card/todo-card.component.html
  src/app/overview/home/todo-card/todo-card.component.ts
  src/app/overview/project/project.component.html
  src/app/review-list/review-list.component.html
  src/app/reviews/reviews.component.html
  src/app/settings/settings.component.html
  src/app/shared/components/achievement-badge/achievement-badge.component.html
  src/app/shared/filestack/filestack.component.html
  src/app/tabs/tabs.component.html
  src/app/topic/topic.component.html
  src/styles.scss
Labels: ready for code review

#767 [AV2-414] Task/generic services unit test
  package-lock.json
  package.json
  src/app/activity/activity.service.ts
  src/app/chat/chat.module.ts
  src/app/go-mobile/go-mobile.component.spec.ts
  src/app/go-mobile/go-mobile.service.spec.ts
  src/app/overview/home/home.service.spec.ts
  src/app/questions/file/file-display/file-display.component.ts
  src/app/reviews/reviews.component.spec.ts
  src/app/services/storage.service.spec.ts
  src/app/services/utils.service.spec.ts
  src/app/services/utils.service.ts
  src/app/shared/directives/float/float.directive.spec.ts
  src/app/shared/pipes/linkify/linkify.pipe.spec.ts
  src/app/shared/pipes/linkify/linkify.pipe.ts
  src/app/shared/pusher/pusher.service.spec.ts
  src/app/switcher/switcher.service.spec.ts
  src/testing/utils.ts
Labels: ready for code review

#783 Task/[AV2-579]/navigation-tabs-disappearing
  src/app/tabs/tabs.component.ts
Labels: changes required

#782 Feature/av2 401/unit test for chat service
  src/app/chat/chat.service.spec.ts
Labels: ready for code review

#798 task/AV2-474/directLink-imersonate-error
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
  src/app/auth/auth.service.spec.ts
  src/app/auth/auth.service.ts
  src/app/switcher/switcher.service.ts
Labels: ready for code review

#788 Task/[AV2-623]/image-orientation
  package-lock.json
  package.json
  src/app/questions/file/file-display/file-display.component.html
  src/app/questions/file/file-display/file-display.component.spec.ts
  src/app/questions/questions.module.ts
  src/app/shared/components/img/img.component.html
  src/app/shared/components/img/img.component.scss
  src/app/shared/components/img/img.component.spec.ts
  src/app/shared/components/img/img.component.ts
  src/app/shared/shared.module.ts
Labels: changes required, ready for code review

#803 Task/AV2-627/handle return url from LTI direct link
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
  src/app/services/storage.service.ts
  src/app/settings/setting.service.ts
  src/app/settings/settings.component.html
  src/app/settings/settings.component.ts
Labels: ready for code review
