Repository intersective/app, pull requests merged in 2020-09, with the labels that each got.

#953 [AV2-742] allow a custom html header and footer in the app
  src/app/app.component.html
  src/app/app.component.ts
  src/styles.scss
Labels: ready for code review

#954 [AV2-724] add changes to clear type message before call api.
  src/app/chat/chat-room/chat-room.component.ts
Labels: ready for code review

#957 Av2 724/develop
  buildspec.yml
  src/app/app.component.html
  src/app/app.component.ts
  src/app/chat/chat-room/chat-room.component.ts
  src/styles.scss
Labels: ready for code review

#956 Develop to Master
  package-lock.json
  src/app/chat/chat-list/chat-list.component.html
  src/app/chat/chat-list/chat-list.component.scss
  src/app/chat/chat-list/chat-list.component.ts
  src/app/chat/chat-room/chat-room.component.html
  src/app/chat/chat-room/chat-room.component.scss
  src/app/chat/chat-room/chat-room.component.ts
  src/app/chat/chat-routing.module.ts
  src/app/chat/chat-view/chat-view.component.html
  src/app/chat/chat-view/chat-view.component.spec.ts
  src/app/chat/chat-view/chat-view.component.ts
  src/app/chat/chat.service.spec.ts
  src/app/chat/chat.service.ts
  src/app/overview/home/home.component.spec.ts
  src/app/overview/home/home.component.ts
  src/app/overview/home/home.service.spec.ts
  src/app/overview/home/home.service.ts
  src/app/services/storage.service.ts
  src/app/shared/pusher/pusher.service.spec.ts
  src/app/shared/pusher/pusher.service.ts
  src/app/tabs/tabs.component.spec.ts
  src/app/tabs/tabs.component.ts
  src/app/tabs/tabs.service.ts
Labels: WIP

#961 [AV2-741] added time out untill finish some background process.
  src/app/auth/auth-direct-login/auth-direct-login.component.spec.ts
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
Labels: ready for code review

#968 [AV2-751] hotfix - Chat messages duplicating when loading previous messages.
  src/app/chat/chat-room/chat-room.component.ts
Labels: ready for code review

#972 Feature/av2 728/quiz answer explanation field issue
  src/app/assessment/assessment.service.ts
  src/app/questions/multiple/multiple.component.html
  src/app/questions/multiple/multiple.component.scss
  src/app/questions/multiple/multiple.component.ts
  src/app/questions/oneof/oneof.component.html
  src/app/questions/oneof/oneof.component.scss
  src/app/questions/oneof/oneof.component.ts
Labels: ready for code review

#977 [AV2-753] Bugfix/meta-slider-compulsory
  src/app/fast-feedback/fast-feedback-submitter.service.ts
  src/app/fast-feedback/fast-feedback.component.spec.ts
  src/app/fast-feedback/fast-feedback.component.ts
  src/app/fast-feedback/fast-feedback.service.spec.ts
  src/app/fast-feedback/fast-feedback.service.ts
Labels: ready for code review

#976 [AV2-753] bugfix/made-backward-compatible
  src/app/fast-feedback/fast-feedback-submitter.service.ts
  src/app/fast-feedback/fast-feedback.component.spec.ts
  src/app/fast-feedback/fast-feedback.component.ts
  src/app/fast-feedback/fast-feedback.service.ts
Labels: changes required

#982 Feature/av2 738/direct link add terms condition page
  src/app/auth/auth-direct-login/auth-direct-login.component.ts
  src/app/auth/auth-registration/auth-registration.component.html
  src/app/auth/auth-registration/auth-registration.component.scss
  src/app/auth/auth-registration/auth-registration.component.ts
  src/app/auth/auth.module.ts
  src/app/auth/terms-conditions-preview/terms-conditions-preview.component.html
  src/app/auth/terms-conditions-preview/terms-conditions-preview.component.scss
  src/app/auth/terms-conditions-preview/terms-conditions-preview.component.spec.ts
  src/app/auth/terms-conditions-preview/terms-conditions-preview.component.ts
  src/styles.scss
Labels: ready for code review
