Repository intersective/app, pull requests merged in 2023-11, with the labels that each got.

#2026 [CORE-6033] When zoom 200% Help screen should be responsive according to viewport size
  projects/v3/src/styles.scss
Labels: ready for code review

#2030 [CORE-6119] auto scrolldown button - prerelease
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.html
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.scss
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.ts
Labels: test passed

#2032 [CORE-6035] sequenced mutilple modals - prerelease
  projects/v3/src/app/components/assessment/assessment.component.ts
  projects/v3/src/app/services/modal.service.spec.ts
  projects/v3/src/app/services/modal.service.ts
  projects/v3/src/app/services/notifications.service.ts
Labels: test passed

#1994 [CORE-6033]When zoom 200% Help screen should be responsive according to viewport size - Golive 2.2.2
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/services/utils.service.ts
  projects/v3/src/styles.scss
Labels: ready for code review

#2033 [CORE-5649] url in chat
  package-lock.json
  package.json
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.html
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.scss
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.ts
  projects/v3/src/app/pages/chat/chat.module.ts
  projects/v3/src/styles.scss
Labels: ready for testing

#2027 Core 6187/UI-enhancement-prerelease
  .github/workflows/dependabot.yml.md
  .github/workflows/p1-au.yml
  .github/workflows/p1-stage.yml
  .github/workflows/p1-uk.yml
  .github/workflows/p1-us.yml
  .github/workflows/p2-aus-appv3.yml
  .github/workflows/p2-aus.yml
  .github/workflows/p2-euk-appv3.yml
  .github/workflows/p2-euk.yml
  .github/workflows/p2-prerelease-appv3.yml
  .github/workflows/p2-prerelease.yml
  .github/workflows/p2-qa.yml
  .github/workflows/p2-sandbox-appv3.yml
  .github/workflows/p2-sandbox-globalapp.yml
  .github/workflows/p2-sandbox.yml
  .github/workflows/p2-stage-appv3.yml
  .github/workflows/p2-stage.yml
  .github/workflows/p2-usa-appv3.yml
  .github/workflows/p2-usa.yml
  .github/workflows/release-lf.yml
  .github/workflows/release-nu.yml
  .github/workflows/release-stage-lf.yml
  .github/workflows/release-tag-validate.yml.md
  projects/v3/src/app/components/activity/activity.component.html
  projects/v3/src/app/components/activity/activity.component.scss
  projects/v3/src/app/pages/v3/v3.page.html
  projects/v3/src/app/pages/v3/v3.page.ts
Labels: test passed
