Repository intersective/app, pull requests merged in 2023-10, with the labels that each got.

#1947 [CORE-6054] [P2-Stage, AppV3] Unearned Badge images not greyed out
  .github/workflows/p2-prerelease-appv3.yml
  projects/v3/src/app/components/achievement-pop-up/achievement-pop-up.component.html
  projects/v3/src/app/components/list-item/list-item.component.html
  projects/v3/src/app/components/list-item/list-item.component.ts
  projects/v3/src/app/pages/home/home.page.html
  projects/v3/src/styles.scss
Labels: ready for code review

#1948 [CORE-6054] [P2-Stage, AppV3] Unearned Badge images not greyed out - GO LIVE
  projects/v3/src/app/components/achievement-pop-up/achievement-pop-up.component.html
  projects/v3/src/app/components/list-item/list-item.component.html
  projects/v3/src/app/components/list-item/list-item.component.ts
  projects/v3/src/app/pages/home/home.page.html
  projects/v3/src/styles.scss
Labels: ready for code review

#1973 [CORE-6038] Update content for placeholder FAQ content in AppV3
  projects/v3/src/app/components/support-popup/support-questions.ts
Labels: ready for code review

#1985 [CORE-6029]Error in fetching checkmark.svg after submitting Pulse Check
  projects/v3/src/app/components/fast-feedback/fast-feedback.component.html
  projects/v3/src/assets/achievement-popup-default.svg
  projects/v3/src/assets/checkmark.svg
  projects/v3/src/assets/icon_zoom_24.svg
  projects/v3/src/assets/waves-light.png
Labels: ready for code review

#1987 [CORE-6029] Error in fetching checkmark.svg after submitting Pulse Check - Prerelease
  projects/v3/src/app/components/fast-feedback/fast-feedback.component.html
  projects/v3/src/assets/achievement-popup-default.svg
  projects/v3/src/assets/checkmark.svg
  projects/v3/src/assets/icon_zoom_24.svg
  projects/v3/src/assets/waves-light.png
Labels: ready for code review

#1993 [CORE-6033] When zoom 200% Help screen should be responsive according to viewport size
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/styles.scss
Labels: ready for code review

#1935 [CORE-6050] notifications list not updated (added additional api) - golive/3.2.4
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
  projects/v3/src/app/pages/assessment-mobile/assessment-mobile.page.ts
  projects/v3/src/app/pages/review-desktop/review-desktop.page.ts
Labels: ready for testing

#1912 [CORE-6015] task/autogrow for all textarea - golive
  projects/v3/src/app/components/activity/activity.component.ts
  projects/v3/src/app/components/file/file.component.html
  projects/v3/src/app/components/multi-team-member-selector/multi-team-member-selector.component.html
  projects/v3/src/app/components/multi-team-member-selector/multi-team-member-selector.component.scss
  projects/v3/src/app/components/multiple/multiple.component.html
  projects/v3/src/app/components/multiple/multiple.component.scss
  projects/v3/src/app/components/oneof/oneof.component.html
  projects/v3/src/app/components/oneof/oneof.component.scss
  projects/v3/src/app/components/support-popup/support-popup.component.html
  projects/v3/src/app/components/team-member-selector/team-member-selector.component.html
  projects/v3/src/app/components/team-member-selector/team-member-selector.component.scss
  projects/v3/src/app/components/text/text.component.html
Labels: test passed

#1975 [CORE-6106] home activity transition - prerelease
  projects/v3/src/app/components/activity/activity.component.html
  projects/v3/src/app/components/activity/activity.component.ts
  projects/v3/src/app/components/topic/topic.component.html
  projects/v3/src/app/components/topic/topic.component.ts
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.html
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.scss
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
  projects/v3/src/app/pages/home/home.page.html
  projects/v3/src/app/pages/home/home.page.ts
  projects/v3/src/app/pages/topic-mobile/topic-mobile.page.html
  projects/v3/src/app/pages/topic-mobile/topic-mobile.page.ts
  projects/v3/src/app/services/activity.service.ts
  projects/v3/src/app/services/home.service.ts
Labels: ready for testing

#1997 hotfix/CORE-6158/last asmt mark as read
  projects/v3/src/app/components/activity/activity.component.html
  projects/v3/src/app/components/activity/activity.component.ts
  projects/v3/src/app/components/topic/topic.component.html
  projects/v3/src/app/components/topic/topic.component.ts
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.html
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.scss
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
  projects/v3/src/app/pages/home/home.page.html
  projects/v3/src/app/pages/home/home.page.ts
  projects/v3/src/app/pages/topic-mobile/topic-mobile.page.html
  projects/v3/src/app/pages/topic-mobile/topic-mobile.page.ts
  projects/v3/src/app/services/activity.service.ts
  projects/v3/src/app/services/assessment.service.ts
  projects/v3/src/app/services/home.service.ts
Labels: ready for testing

#2015 [CORE-6033] When zoom 200% Help screen should be responsive according to viewport size
  projects/v3/src/app/services/utils.service.ts
Labels: ready for code review
