Repository intersective/app, pull requests merged in 2023-05, with the labels that each got.

#1793 [AV2-1376] add hubspot support form and questions popup
  projects/v3/src/app/components/components.module.ts
  projects/v3/src/app/components/support-popup/support-popup.component.html
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/components/support-popup/support-popup.component.spec.ts
  projects/v3/src/app/components/support-popup/support-popup.component.ts
  projects/v3/src/app/components/support-popup/support-questions.ts
  projects/v3/src/app/pages/settings/settings.page.html
  projects/v3/src/app/pages/settings/settings.page.spec.ts
  projects/v3/src/app/pages/settings/settings.page.ts
  projects/v3/src/app/personalised-header/personalised-header.component.html
  projects/v3/src/app/personalised-header/personalised-header.component.scss
  projects/v3/src/app/personalised-header/personalised-header.component.ts
  projects/v3/src/app/services/demo.service.ts
  projects/v3/src/app/services/hubspot.service.spec.ts
  projects/v3/src/app/services/hubspot.service.ts
  projects/v3/src/app/services/request.interceptor.ts
  projects/v3/src/app/services/shared.service.ts
  projects/v3/src/app/services/storage.service.ts
  projects/v3/src/app/services/utils.service.ts
  projects/v3/src/environments/environment.custom.ts
  projects/v3/src/styles.scss
  projects/v3/src/theme/variables.scss
Labels: ready for code review

#1796 [AV2-1376] Add Hubspot Support Form and Common Questions Popup
  projects/v3/src/app/services/hubspot.service.ts
Labels: ready for code review

#1797 [AV2-1376] hide support button on mobile.
  projects/v3/src/app/personalised-header/personalised-header.component.ts
Labels: ready for code review

#1802 [AV2-1376] Updated mobile Styles in support button
  projects/v3/src/app/personalised-header/personalised-header.component.html
  projects/v3/src/app/personalised-header/personalised-header.component.scss
  projects/v3/src/app/personalised-header/personalised-header.component.ts
Labels: ready for code review

#1801 [AV2-1423] Content of some support questions doesn't match the content in the document provided
  projects/v3/src/app/components/support-popup/support-questions.ts
Labels: ready for code review

#1803 [AV2-1430] "Thank you" message is displayed in empty submit
  projects/v3/src/app/components/support-popup/support-popup.component.html
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/components/support-popup/support-popup.component.ts
Labels: ready for code review

#1818 [AV2-1430] thank you message is displayed for empty form submit
  projects/v3/src/app/components/support-popup/support-popup.component.html
  projects/v3/src/app/components/support-popup/support-popup.component.ts
Labels: ready for code review

#1819 [AV2-1430] Thank you message is displayed for empty form submit ( golive )
  angular.json
  projects/v3/src/app/components/support-popup/support-popup.component.html
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/components/support-popup/support-popup.component.ts
  projects/v3/src/app/services/hubspot.service.ts
  projects/v3/src/app/services/utils.service.ts
Labels: ready for code review

#1822 [AV2-1424] Last name missing in submit data
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/services/demo.service.ts
  projects/v3/src/app/services/experience.service.ts
  projects/v3/src/app/services/hubspot.service.ts
  projects/v3/src/app/services/storage.service.ts
  projects/v3/src/styles.scss
Labels: ready for code review

#1799 [AV2-1344] forced logout (golive)
  projects/v3/src/app/pages/home/home.page.ts
  projects/v3/src/app/services/home.service.ts
Labels: test passed

#1825 [AV2-1431] fixed correct response but wrong format from filestack
  projects/v3/src/app/components/support-popup/support-popup.component.ts
  projects/v3/src/app/services/request.interceptor.ts
Labels: ready for testing

#1823 [AV2-1424] Last name missing in submit data (Golive)
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/services/demo.service.ts
  projects/v3/src/app/services/experience.service.ts
  projects/v3/src/app/services/hubspot.service.ts
  projects/v3/src/app/services/storage.service.ts
  projects/v3/src/styles.scss
Labels: ready for code review

#1810 [AV2-1403] hubspot support integration (golive)
  angular.json
  projects/v3/src/app/components/components.module.ts
  projects/v3/src/app/components/support-popup/support-popup.component.html
  projects/v3/src/app/components/support-popup/support-popup.component.scss
  projects/v3/src/app/components/support-popup/support-popup.component.spec.ts
  projects/v3/src/app/components/support-popup/support-popup.component.ts
  projects/v3/src/app/components/support-popup/support-questions.ts
  projects/v3/src/app/pages/settings/settings.page.html
  projects/v3/src/app/pages/settings/settings.page.spec.ts
  projects/v3/src/app/pages/settings/settings.page.ts
  projects/v3/src/app/personalised-header/personalised-header.component.html
  projects/v3/src/app/personalised-header/personalised-header.component.scss
  projects/v3/src/app/personalised-header/personalised-header.component.ts
  projects/v3/src/app/services/demo.service.ts
  projects/v3/src/app/services/experience.service.ts
  projects/v3/src/app/services/hubspot.service.spec.ts
  projects/v3/src/app/services/hubspot.service.ts
  projects/v3/src/app/services/request.interceptor.ts
  projects/v3/src/app/services/shared.service.ts
  projects/v3/src/app/services/storage.service.ts
  projects/v3/src/app/services/utils.service.ts
  projects/v3/src/environments/environment.custom.ts
  projects/v3/src/styles.scss
  projects/v3/src/theme/variables.scss
Labels: ready for code review
