Repository intersective/app, pull requests merged in 2024-07, with the labels that each got.

#2127 [CORE-6551] Task/http 429 handled
  projects/v3/src/app/components/assessment/assessment.component.ts
  projects/v3/src/app/services/assessment.service.ts
Labels: test passed

#2176 [CORE-6675] check latest subsmission status before submission
  projects/v3/src/app/components/assessment/assessment.component.ts
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
  projects/v3/src/app/services/assessment.service.ts
Labels: test passed

#2182 [CORE-6241] Hotfix/offline check with ping
  projects/request/src/lib/request.service.ts
  projects/v3/src/app/services/network.service.ts
Labels: ready for testing

#2186 [CORE-6655] Typing event shows for wrong channels - Trunk
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.ts
  projects/v3/src/app/services/pusher.service.ts
Labels: ready for code review

#2183 [CORE-6678] Hotfix/check submission status prerelease
  projects/v3/src/app/components/multi-team-member-selector/multi-team-member-selector.component.html
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
  projects/v3/src/app/pages/assessment-mobile/assessment-mobile.page.ts
  projects/v3/src/app/pages/review-desktop/review-desktop.page.ts
  projects/v3/src/app/services/notifications.service.ts
Labels: test passed

#2173 [CORE-6673] revalidate stale milestone unlock indicator on visit
  projects/v3/src/app/components/activity/activity.component.ts
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
  projects/v3/src/app/pages/home/home.page.ts
  projects/v3/src/app/services/unlock-indicator.service.ts
Labels: test passed

#2191 [CORE-6653] retire core jwt refresh - prerelease
  projects/v3/src/app/pages/chat/chat-view/chat-view.component.ts
  projects/v3/src/app/pages/devtool/devtool.page.ts
  projects/v3/src/app/services/auth.service.ts
  projects/v3/src/app/services/request.interceptor.ts
  projects/v3/src/app/services/shared.service.ts
Labels: test passed

#2185 [CORE-6655] Typing event shows for wrong channels - Golive
  projects/v3/src/app/pages/chat/chat-room/chat-room.component.ts
  projects/v3/src/app/services/pusher.service.ts
Labels: ready for code review

#2197 [CORE-6696] jumpy scrolling on home screen
  projects/v3/src/app/pages/home/home.page.html
  projects/v3/src/app/pages/home/home.page.ts
  projects/v3/src/app/services/home.service.ts
  projects/v3/src/app/services/utils.service.ts
Labels: test passed

#2180 [CORE-6676] review from magiclink, avoid getActivity()
  projects/v3/src/app/pages/assessment-mobile/assessment-mobile.page.ts
  projects/v3/src/app/services/activity.service.ts
  projects/v3/src/app/services/assessment.service.ts
Labels: test passed

#2202 [CORE-6693] Hotfix/act scrolling reset scroll
  projects/v3/src/app/components/activity/activity.component.html
  projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
Labels: test passed

#2206 [CORE-6606] Use Graphql url for chat related APIs
  projects/v3/src/app/services/apollo.service.ts
  projects/v3/src/app/services/chat.service.spec.ts
  projects/v3/src/app/services/chat.service.ts
  projects/v3/src/app/services/notifications.service.spec.ts
  projects/v3/src/app/services/notifications.service.ts
  projects/v3/src/app/services/pusher.service.spec.ts
  projects/v3/src/app/services/pusher.service.ts
  projects/v3/src/app/services/shared.service.ts
Labels: ready for code review
